# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_client.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(482, 257)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.break_btn = QtWidgets.QPushButton(self.centralwidget)
        self.break_btn.setObjectName("break_btn")
        self.gridLayout.addWidget(self.break_btn, 1, 2, 1, 1)
        self.ip_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.ip_edit.setObjectName("ip_edit")
        self.gridLayout.addWidget(self.ip_edit, 0, 1, 1, 1)
        self.port_label = QtWidgets.QLabel(self.centralwidget)
        self.port_label.setObjectName("port_label")
        self.gridLayout.addWidget(self.port_label, 1, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 3, 0, 4, 3)
        self.connect_btn = QtWidgets.QPushButton(self.centralwidget)
        self.connect_btn.setObjectName("connect_btn")
        self.gridLayout.addWidget(self.connect_btn, 0, 2, 1, 1)
        self.ip = QtWidgets.QLabel(self.centralwidget)
        self.ip.setObjectName("ip")
        self.gridLayout.addWidget(self.ip, 0, 0, 1, 1)
        self.port_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.port_edit.setObjectName("port_edit")
        self.gridLayout.addWidget(self.port_edit, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 3, 1, 1)
        self.file_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.file_edit.setObjectName("file_edit")
        self.gridLayout.addWidget(self.file_edit, 1, 3, 1, 1)
        self.load_btn = QtWidgets.QPushButton(self.centralwidget)
        self.load_btn.setObjectName("load_btn")
        self.gridLayout.addWidget(self.load_btn, 3, 3, 1, 1)
        self.play_btn = QtWidgets.QPushButton(self.centralwidget)
        self.play_btn.setObjectName("play_btn")
        self.gridLayout.addWidget(self.play_btn, 4, 3, 1, 1)
        self.stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.stop_btn.setObjectName("stop_btn")
        self.gridLayout.addWidget(self.stop_btn, 6, 3, 1, 1)
        self.push_btn = QtWidgets.QPushButton(self.centralwidget)
        self.push_btn.setObjectName("push_btn")
        self.gridLayout.addWidget(self.push_btn, 5, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 482, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "clinet"))
        self.break_btn.setText(_translate("MainWindow", "断开"))
        self.port_label.setText(_translate("MainWindow", "端口号："))
        self.connect_btn.setText(_translate("MainWindow", "连接"))
        self.ip.setText(_translate("MainWindow", "服务器ip："))
        self.label.setText(_translate("MainWindow", "连接已断开"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.load_btn.setText(_translate("MainWindow", "加载视频"))
        self.play_btn.setText(_translate("MainWindow", "播放"))
        self.stop_btn.setText(_translate("MainWindow", "停止"))
        self.push_btn.setText(_translate("MainWindow", "暂停"))
        self.textEdit.setFocusPolicy(QtCore.Qt.NoFocus)
